# 1. Write a Python Program to Add Two Matrices?


In [1]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[1,2,3],[4,5,6],[7,8,9]]
x=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(a)):
    for j in range(len(a[0])):
        x[i][j]=a[i][j]+b[i][j]

for r in x:
    print(r)


[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


In [2]:
# using numpy package
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

#  2. Write a Python Program to Multiply Two Matrices?


In [3]:
# this multiplication is index to index multiplication
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[1,2,3],[4,5,6],[7,8,9]]
x=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(a)):
    for j in range(len(a[0])):
        x[i][j]=a[i][j]*b[i][j]

for r in x:
    print(r)


[1, 4, 9]
[16, 25, 36]
[49, 64, 81]


In [4]:
# using numpy package
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

#  3. Write a Python Program to Transpose a Matrix?


In [5]:
a=[[1,2,3],[4,5,6],[7,8,9]]
x=[[0,0,0],[0,0,0],[0,0,0]]

for i in range(len(a)):
    for j in range(len(a[0])):
        x[j][i]=a[i][j]
for r in x:
    print(r)

[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [6]:
# using numpy package 
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#  4. Write a Python Program to Sort Words in Alphabetic Order?


In [7]:
# Capital letter have less weight than small letter
#  A =65
# a=97
sentence='Hey my name is kishan kumar this is my assignment_8 from Data Science Master course'
output=sentence.split()
output.sort()
print(output)
for i in output:
    print(i)

['Data', 'Hey', 'Master', 'Science', 'assignment_8', 'course', 'from', 'is', 'is', 'kishan', 'kumar', 'my', 'my', 'name', 'this']
Data
Hey
Master
Science
assignment_8
course
from
is
is
kishan
kumar
my
my
name
this


# 5. Write a Python Program to Remove Punctuation From a String?

In [8]:
p="{'}[]():;.,-/*?!@#"
s="H'e.y (m,[y]) n@me is k!s#@n"
r=''

for i in s:
    if i  not in p:
#         print(i)
        r=r+i
print(r)

Hey my nme is ksn
